version:  "3.9"
services:
  db:
    image: postgres
    container_name: car-rentals-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=car-rentals-db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: car-rentals
    ports:
      - 3000:3000
    volumes:
      - .:/user/app
    links:
      - db
    depends_on:
      - db
    

volumes:
  pgdata:
    driver: local